spring.application.name=micuenta 
server.port=8080

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456789

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=bXktc3VwZXItc2VjdXJlLWp3dC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHktY2hhbmdlLW1lLW5vdy0xMjM0NTY3ODkw
security.jwt.expiration-minutes=120 