spring.application.name=micuenta 
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/mi_cuenta
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=isabella2007


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


security.jwt.secret=bXktc3VwZXItc2VjdXJlLWp3dC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHktY2hhbmdlLW1lLW5vdy0xMjM0NTY3ODkw
security.jwt.expiration-minutes=120